version: "3"

services:
 insurance-service:
    platform: linux/arm64
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: claim-service
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=vincic1!
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://summer-school.postgres.database.azure.com:5432/claim
    ports:
      - "50002:8080"