version: "3"

services:
  insurance-service:
    platform: linux/arm64
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: insured-person-service
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=vincic1!
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://summer-school.postgres.database.azure.com:5432/insuredperson
    ports:
      - "50003:8080"